import SpotifyWrapper from 'spotify-wrapper-veloso';

const Spotify = new SpotifyWrapper({
  token: 'BQA0SnuTc_ZG7yNg5GozskckCETpYVRmYVg-WFA-HA3JGSeesNyh2tBL1ytpDV-bLlmv_TrQuAy4QgOQe2cwzv6NnvZaJIkPHH5MtB4dZRRgCODdd9YeZmfbDbQ6fbwh_5RG2I3u8LIy-Qc6Gl9WeNX__mQ6HaWzwaExjHr4v2Qo-Xxo5kzCZ-uo6kMfGQqmKAaEug7EUzWvZcel3osX4jzIlAxbdr8ZuggPdPB4ao5BlLKzT6xVs30CaQhqNTYy3tG-C5fJpwPR1QzTklaHao9UCA8'
});

export default Spotify;
