import SpotifyWrapper from 'spotify-wrapper-veloso';

const Spotify = new SpotifyWrapper({
  token: 'BQCtSHfVQoViH_gySA1CYrMK0DbeqIBFjX1zS4Bk7v8skVCOg4L-qzrzRzCosm-kmssUMIfeE6rZKVC9Ws08MHB44s6Ri1fIc_cYUUoHZSkoYwkNTHRSOOaoONRtpWLDKrFpB52sHfOxRiA3VUDYkj-su0fdu5Dhe70y8RarMHcoEmy5eE3iEcoU_BNQzWeJ8nPRzzcwvhZZPEeraSUyg93aSPZRcJ7zoao36LXCNHKdOWbd3__doCMFI3gee7iZE8Kp6mv0m6xW6od7oDEVgIzlS9E'
});

export default Spotify;
